server:
  port: 8081

spring:
  application:
    name: user-bff
  graphql:
    graphiql:
      enabled: true
    path: /graphql
    schema:
      locations: classpath:graphql/

middleware:
  url: https://${MIDDLEWARE_HOST:localhost}:8443

mtls:
  client:
    keystore:
      path: ${KEYSTORE_PATH:/opt/user-bff/certs/client-keystore.p12}
      password: ${KEYSTORE_PASSWORD:changeit}
    truststore:
      path: ${TRUSTSTORE_PATH:/opt/user-bff/certs/client-truststore.p12}
      password: ${TRUSTSTORE_PASSWORD:changeit}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
